site_name: DIY-CNC-machine
site_url: https://sohnemann.github.io/DIY-CNC-machine/
theme:
  name: material
  scheme: default
  palette:
    primary: red
nav:
- Main frame: 01-main-frame.md
- Y-axis: 02-y-axis.md
- X-axis and Z-axis: 03-x-axis-and-z-axis.md
- Stepper motors and end-stops: 04-stepper-motors-and-end-stops.md
- Router: 05-router.md
- Electronic boxes: 06-electronic-boxes.md
- Electrical wiring and connect components: 07-electrical-wiring-and-connect-components.md
- Wasteboard: 08-wasteboard.md
- Dust shoe: 09-dust-shoe.md
- Software: 10-software.md
- G-Code sender: 11-g-code-sender.md
- Final notes: 12-final-notes.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
